application: tasks-demo
version: 2
runtime: python
api_version: 1

handlers:
- url: /static/(.*)/detect-browser
  static_files: static/\1/detect-browser
  upload: static/(.*)/detect-browser
  mime_type: text/javascript

- url: /tasks/(..)
  static_files: static/tasks/\1/index.html
  upload: static/tasks/(.*)/index.html
  mime_type: text/html

- url: /tasks
  static_files: static/tasks/en/demo/index.html
  upload: static/tasks/en/demo/index.html
  mime_type: text/html

- url: /
  static_files: static/tasks/en/demo/index.html
  upload: static/tasks/en/demo/index.html
  mime_type: text/html
  
- url: /static
  static_dir: static
  
- url: /mailtest
  script: main.python

- url: /mailer
  script: main.python

- url: /tasks
  static_dir: static/tasks

- url: /.*
  script: main.py